gui:
  theme:
    activeBorderColor:
      - '#89b4fa' # catppuccin blue
    inactiveBorderColor:
      - '#45475a' # catppuccin surface1
  scrollHeight: 2
  scrollPastBottom: true
  mouseEvents: true
  skipStashWarning: true
  showFileTree: true
  showRandomTip: false

git:
  paging:
    colorArg: always
    pager: delta --dark --paging=never
  commit:
    signOff: false
  merging:
    manualCommit: false

os:
  editPreset: 'nvim'